# Statistics
    Academic discipline dealing with all aspects of data
    
### Perspectives:
    - art of summerizing data -> make data comprehensible
    - science of uncertainty -> most info in the world in uncertain
    - science of decisions -> ultimate goal of statistics
    - science of variation -> central tendency and spread
    - art of forecasting -> predictions
    - science of measurement and data collection

### Foundations of data
#### Sources of data
    - Designed data -> "artificially collected" (surveys, studies etc)
    - Organic data (process generated)
    - for both, data needs to be IID -> independant, identically distributed
#### Types of data
    - Weight -> numeric, continuos
    - No. of kids -> numeric, discrete
    - Age group (child, adult, elder) -> categorical, ordered
    - Gender -> categorical, unordered
    
    Practical Note:
        Gender represented as: M / F
                           or: 0 / 1 -> still unordered but thought of as ordered
        M [ 1 0 ] 
        F [ 0 1 ]
        "one-hot vector representation" 
        
### Variables
    |__Quantitative(numeric)
    |  |__Continuous
    |  |__Discrete
    |   
    |__Qualitative(categorical)
       |__Ordinal(ranked)
       |__Nominal(unranked)

In [2]:
import pandas as pd

In [3]:
url = "data/nhanes_2015_2016.csv"
da = pd.read_csv(url)

In [4]:
da.columns

Index(['SEQN', 'ALQ101', 'ALQ110', 'ALQ130', 'SMQ020', 'RIAGENDR', 'RIDAGEYR',
       'RIDRETH1', 'DMDCITZN', 'DMDEDUC2', 'DMDMARTL', 'DMDHHSIZ', 'WTINT2YR',
       'SDMVPSU', 'SDMVSTRA', 'INDFMPIR', 'BPXSY1', 'BPXDI1', 'BPXSY2',
       'BPXDI2', 'BMXWT', 'BMXHT', 'BMXBMI', 'BMXLEG', 'BMXARML', 'BMXARMC',
       'BMXWAIST', 'HIQ210'],
      dtype='object')

In [5]:
da['BMXWT'].mean()

np.float64(81.34267560889516)

In [6]:
da['DMDEDUC2'].unique()

array([ 5.,  3.,  4.,  2., nan,  1.,  9.])

In [7]:
g = da['RIAGENDR']
g

0       1
1       1
2       1
3       2
4       2
       ..
5730    2
5731    1
5732    2
5733    1
5734    2
Name: RIAGENDR, Length: 5735, dtype: int64

In [8]:
g.unique()

array([1, 2])

## One Hot Encoding

In [9]:
B = ['bird', 'cat', 'dog', 'cat', 'bird', 'bird']
d = {'categorical': B}
df = pd.DataFrame(d)

In [10]:
df

  categorical
0        bird
1         cat
2         dog
3         cat
4        bird
5        bird

In [11]:
df['categorical']

0    bird
1     cat
2     dog
3     cat
4    bird
5    bird
Name: categorical, dtype: object

In [17]:
# 'dummies' is used to create columns corresponding to unique values
dfDummies = pd.get_dummies(df['categorical'], prefix = 'category')

In [18]:
dfDummies

   category_bird  category_cat  category_dog
0           True         False         False
1          False          True         False
2          False         False          True
3          False          True         False
4           True         False         False
5           True         False         False

In [14]:
dfDummies.values

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False]])